import type {
  ContractGraph,
  ContractGraphNode,
  CrossContractArg,
  CrossContractArgSource,
  CrossContractType,
} from "./schema"

/**
 * Emission helpers for the CrossContractCall block.
 *
 * A CrossContractCall node compiles to two pieces of Rust:
 *
 * 1. A module-level client declaration generated by the `soroban_sdk::contractclient`
 *    macro — the SDK's client generator for an external contract interface:
 *
 *    ```rust
 *    #[soroban_sdk::contractclient(name = "CrossContract1Client")]
 *    pub trait CrossContract1 {
 *        fn stake(env: Env, caller: Address, amount: i128) -> i128;
 *    }
 *    ```
 *
 * 2. The invocation itself inside `execute`, optionally bound to a name so that
 *    downstream Condition blocks can use the result as an operand:
 *
 *    ```rust
 *    let stake_result: i128 = CrossContract1Client::new(&env, &target_contract).stake(&caller, &amount);
 *    ```
 *
 * The target address is supplied at invocation time through a derived
 * `target_contract` parameter (one per CrossContractCall node), while the
 * block's configured `targetContractId` is emitted as a documentation comment.
 */

export const DEFAULT_RETURN_TYPE: CrossContractType = "i128"

/** Rust identifier fallback used when a configured name is empty or unusable. */
const IDENT_FALLBACK = "arg"

/** Converts arbitrary user input into a safe snake_case Rust identifier. */
export function sanitizeRustIdent(value: string | undefined, fallback = IDENT_FALLBACK): string {
  const cleaned = (value ?? "")
    .trim()
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/^_+/, "")
    .toLowerCase()

  if (cleaned.length === 0) return fallback
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned
}

/** Converts arbitrary user input into a safe Soroban `symbol_short!` payload (max 9 chars). */
export function sanitizeSymbolLiteral(value: string | undefined, fallback = "key"): string {
  const cleaned = (value ?? "").replace(/[^a-zA-Z0-9_]/g, "_").slice(0, 9)
  return cleaned.length > 0 ? cleaned : fallback
}

function escapeRustString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

/** Trait name declared for the Nth (0-based) CrossContractCall node. */
export function crossContractTraitName(index: number): string {
  return `CrossContract${index + 1}`
}

/** Generated client struct name for the Nth (0-based) CrossContractCall node. */
export function crossContractClientName(index: number): string {
  return `${crossContractTraitName(index)}Client`
}

/** `execute` parameter carrying the target address for the Nth (0-based) node. */
export function crossContractTargetParam(index: number): string {
  return index === 0 ? "target_contract" : `target_contract_${index + 1}`
}

/** Returns the CrossContractCall nodes of an execution order, in call order. */
export function getCrossContractNodes(nodes: ContractGraphNode[]): ContractGraphNode[] {
  return nodes.filter((node) => node.type === "CrossContractCall")
}

/** Normalized argument list of a CrossContractCall node. */
export function getCrossContractArgs(node: ContractGraphNode): CrossContractArg[] {
  const args = node.data.params?.targetArgs
  return Array.isArray(args) ? args : []
}

function argSource(arg: CrossContractArg): CrossContractArgSource {
  return arg.source ?? "literal"
}

function argRustType(arg: CrossContractArg): CrossContractType {
  return (arg.rustType || DEFAULT_RETURN_TYPE) as CrossContractType
}

/** Return type of a node's call — `undefined` when the result is discarded. */
export function getReturnType(node: ContractGraphNode): CrossContractType | undefined {
  const binding = node.data.params?.returnBinding?.trim()
  if (!binding) return undefined
  return (node.data.params?.returnType || DEFAULT_RETURN_TYPE) as CrossContractType
}

/** Every `returnBinding` declared in a graph — usable as a Condition operand. */
export function getReturnBindings(graph: ContractGraph): string[] {
  return getCrossContractNodes(graph.nodes)
    .map((node) => node.data.params?.returnBinding?.trim())
    .filter((binding): binding is string => Boolean(binding))
    .map((binding) => sanitizeRustIdent(binding, "call_result"))
}

/** Rust expression reading a value of `rustType` out of instance storage. */
function storageReadExpr(key: string, rustType: CrossContractType): string {
  const symbol = `&symbol_short!("${sanitizeSymbolLiteral(key)}")`

  switch (rustType) {
    case "i128":
      return `env.storage().instance().get::<_, i128>(${symbol}).unwrap_or(0)`
    case "bool":
      return `env.storage().instance().get::<_, bool>(${symbol}).unwrap_or(false)`
    default:
      return `env.storage().instance().get::<_, ${rustType}>(${symbol}).unwrap()`
  }
}

/** Rust expression for a literal of `rustType`. */
function literalExpr(value: string, rustType: CrossContractType): string {
  const raw = value.trim()

  switch (rustType) {
    case "i128":
      return /^-?\d+$/.test(raw) ? raw : "0"
    case "bool":
      return raw.toLowerCase() === "true" ? "true" : "false"
    case "Symbol":
      return `symbol_short!("${sanitizeSymbolLiteral(raw, "none")}")`
    case "Address":
    default:
      return `Address::from_string(&String::from_str(&env, "${escapeRustString(raw)}"))`
  }
}

/** Rust expression passed for a single argument at the call site. */
export function emitCrossContractArgExpr(arg: CrossContractArg): string {
  const rustType = argRustType(arg)

  switch (argSource(arg)) {
    case "invocationArg":
      return sanitizeRustIdent(arg.value, "caller")
    case "storageKey":
      return storageReadExpr(arg.value, rustType)
    case "literal":
    default:
      return literalExpr(arg.value, rustType)
  }
}

/**
 * Emits the module-level `soroban_sdk::contractclient` declaration for a node.
 * `index` is the node's 0-based position among the graph's CrossContractCall nodes.
 */
export function emitCrossContractClient(node: ContractGraphNode, index: number): string {
  const fnName = sanitizeRustIdent(node.data.params?.targetFunction, "call")
  const args = getCrossContractArgs(node)
  const returnType = getReturnType(node)

  const params = ["env: Env", ...args.map((arg) => `${sanitizeRustIdent(arg.name)}: ${argRustType(arg)}`)]
  const returns = returnType ? ` -> ${returnType}` : ""
  const contractId = node.data.params?.targetContractId?.trim()

  return `#[soroban_sdk::contractclient(name = "${crossContractClientName(index)}")]
pub trait ${crossContractTraitName(index)} {${contractId ? `\n    // Target contract: ${contractId}` : ""}
    fn ${fnName}(${params.join(", ")})${returns};
}`
}

/**
 * Emits the invocation statement for a CrossContractCall node, indented to sit
 * inside the generated `execute` function body.
 */
export function emitCrossContractCall(node: ContractGraphNode, index: number, comment: string): string {
  const fnName = sanitizeRustIdent(node.data.params?.targetFunction, "call")
  const args = getCrossContractArgs(node)
  const returnType = getReturnType(node)
  const client = crossContractClientName(index)
  const target = crossContractTargetParam(index)

  const argList = args.map((arg) => `&${emitCrossContractArgExpr(arg)}`).join(", ")
  const invocation = `${client}::new(&env, &${target}).${fnName}(${argList});`

  if (!returnType) {
    return `        // ${comment}\n        ${invocation}`
  }

  const binding = sanitizeRustIdent(node.data.params?.returnBinding, "call_result")
  return `        // ${comment}\n        let ${binding}: ${returnType} = ${invocation}`
}

/**
 * Extra `soroban_sdk` imports required by the CrossContractCall nodes of a graph.
 */
export function collectCrossContractImports(nodes: ContractGraphNode[]): string[] {
  const crossNodes = getCrossContractNodes(nodes)
  if (crossNodes.length === 0) return []

  // Every call takes its target address from a derived `Address` parameter.
  const imports = new Set<string>(["Address"])

  for (const node of crossNodes) {
    if (getReturnType(node) === "Symbol") imports.add("Symbol")

    for (const arg of getCrossContractArgs(node)) {
      const rustType = argRustType(arg)
      if (rustType === "Symbol") imports.add("Symbol")

      switch (argSource(arg)) {
        case "storageKey":
          imports.add("symbol_short")
          break
        case "literal":
          if (rustType === "Symbol") imports.add("symbol_short")
          if (rustType === "Address") imports.add("String")
          break
        default:
          break
      }
    }
  }

  return Array.from(imports)
}

/**
 * Derived `execute` parameters required by the CrossContractCall nodes of a graph:
 * every argument sourced from an invocation argument that no other block already
 * declares, followed by one target address parameter per call node.
 *
 * `existing` lists parameter names already derived from the other block types so
 * that shared names (e.g. `caller`, `amount`) are not declared twice.
 */
export function crossContractParams(
  nodes: ContractGraphNode[],
  existing: Iterable<string> = []
): Array<{ name: string; rustType: string }> {
  const crossNodes = getCrossContractNodes(nodes)
  if (crossNodes.length === 0) return []

  const declared = new Set<string>(existing)
  const params: Array<{ name: string; rustType: string }> = []

  for (const node of crossNodes) {
    for (const arg of getCrossContractArgs(node)) {
      if (argSource(arg) !== "invocationArg") continue

      const name = sanitizeRustIdent(arg.value, "caller")
      if (declared.has(name)) continue

      declared.add(name)
      params.push({ name, rustType: argRustType(arg) })
    }
  }

  return [
    ...params,
    ...crossNodes.map((_, index) => ({
      name: crossContractTargetParam(index),
      rustType: "Address",
    })),
  ]
}

/**
 * Module-level client declarations for every CrossContractCall node of a graph,
 * ready to be placed above the generated contract struct.
 */
export function emitCrossContractClients(nodes: ContractGraphNode[]): string {
  const crossNodes = getCrossContractNodes(nodes)
  if (crossNodes.length === 0) return ""

  return crossNodes.map((node, index) => emitCrossContractClient(node, index)).join("\n\n")
}
